import Link from "next/link";
import { ArrowRight, BarChart3, Boxes, CircleDollarSign, Landmark, ReceiptText, ShoppingCart, UsersRound } from "lucide-react";
import { ScrollReveal } from "@/components/marketing/scroll-reveal";

const capabilities = [
  [Boxes, "Productos y stock", "Catálogo, depósitos, movimientos, lotes, series y alertas con una sola fuente operativa."],
  [ShoppingCart, "Ventas y clientes", "Pedidos de Vase Business llegan en segundos y mantienen la historia comercial ordenada."],
  [ReceiptText, "Facturación y compras", "Circuitos administrativos conectados para trabajar sin planillas paralelas."],
  [CircleDollarSign, "Tesorería", "Caja, bancos, cobros, pagos y flujo proyectado con trazabilidad."],
  [BarChart3, "Reportes", "Lecturas comerciales y operativas listas para decidir, exportar y compartir."],
  [UsersRound, "Equipos y permisos", "Accesos por empresa y usuario desde la misma identidad segura de Vase."],
] as const;

export default function VaseManagementPage() {
  return <div className="pb-24 text-[#17231b]">
    <section className="relative overflow-hidden px-6 pb-24 pt-40 lg:px-10"><div className="pointer-events-none absolute right-[-8rem] top-20 size-[32rem] rounded-full border border-[#bfd0c4]/50" /><div className="mx-auto grid max-w-[92rem] gap-14 lg:grid-cols-[1.05fr_.95fr] lg:items-end"><ScrollReveal><p className="text-[11px] font-bold uppercase tracking-[.24em] text-[#26704a]">El sistema de gestión de Vase</p><h1 className="mt-6 max-w-4xl font-[family-name:var(--font-newsreader)] text-6xl leading-[.98] tracking-[-.055em] sm:text-8xl">La operación completa, <span className="italic font-light text-[#26704a]">en el mismo ritmo.</span></h1><p className="mt-8 max-w-2xl text-lg leading-8 text-[#526159]">Management conecta stock, ventas, clientes y administración con Vase Business y Vase Labs. Sin tokens manuales, sin doble carga y sin perder control.</p><div className="mt-10 flex flex-wrap gap-3"><Link href="/register" className="inline-flex min-h-13 items-center rounded-full bg-[#17633f] px-7 font-semibold text-white">Solicitar activación <ArrowRight className="ml-2 size-4" /></Link><Link href="/precios#management" className="inline-flex min-h-13 items-center rounded-full border border-[#b8c7bd] px-7 font-semibold">Ver precios</Link></div></ScrollReveal><ScrollReveal delay={.08}><div className="rounded-[2.2rem] border border-[#d8e1da] bg-[#f8faf8] p-7 shadow-[0_32px_90px_rgba(28,62,41,.1)]"><div className="flex items-center justify-between border-b border-[#dfe6e1] pb-5"><div><small className="text-[#718078]">Estado operativo</small><strong className="block text-xl">Todo sincronizado</strong></div><span className="rounded-full bg-[#dff3e6] px-3 py-1 text-xs font-bold text-[#17633f]">En línea</span></div><div className="mt-6 grid grid-cols-2 gap-3"><div className="rounded-2xl bg-white p-5"><Landmark className="size-5 text-[#26704a]" /><b className="mt-7 block text-3xl">1.248</b><small className="text-[#718078]">productos activos</small></div><div className="rounded-2xl bg-[#173d2b] p-5 text-white"><ShoppingCart className="size-5 text-[#91ddb1]" /><b className="mt-7 block text-3xl">38</b><small className="text-white/60">pedidos hoy</small></div></div><p className="mt-5 text-sm text-[#66736b]">Management → Business → Labs<br />Última actualización hace 18 segundos</p></div></ScrollReveal></div></section>
    <section className="mx-auto max-w-[92rem] px-6 lg:px-10"><div className="grid gap-px overflow-hidden rounded-[2rem] border border-[#dce4de] bg-[#dce4de] md:grid-cols-2 lg:grid-cols-3">{capabilities.map(([Icon, title, body], index) => <ScrollReveal key={title} delay={index * .04} className="bg-[#f8faf8] p-8"><Icon className="size-6 text-[#26704a]" /><h2 className="mt-12 font-[family-name:var(--font-newsreader)] text-3xl tracking-[-.03em]">{title}</h2><p className="mt-4 leading-7 text-[#58675f]">{body}</p></ScrollReveal>)}</div></section>
    <ScrollReveal><section className="mx-auto mt-24 max-w-[92rem] px-6 lg:px-10"><div className="rounded-[2.4rem] bg-[#163b29] px-8 py-16 text-white sm:px-14"><p className="text-xs font-bold uppercase tracking-[.22em] text-[#8ee0af]">Una fuente, tres productos</p><h2 className="mt-5 max-w-4xl font-[family-name:var(--font-newsreader)] text-5xl tracking-[-.045em] sm:text-6xl">Actualizá una vez. Vendé, respondé y administrá con los mismos datos.</h2><p className="mt-6 max-w-2xl text-lg leading-8 text-white/68">Business publica y recibe pedidos. Labs conoce el catálogo autorizado. Management conserva la verdad operativa.</p></div></section></ScrollReveal>
  </div>;
}
