CREATE TABLE `ConversationOrderDraft` (
  `id` VARCHAR(191) NOT NULL,
  `conversationId` VARCHAR(191) NOT NULL,
  `assistantId` VARCHAR(191) NOT NULL,
  `globalTenantId` VARCHAR(191) NOT NULL,
  `state` ENUM('COLLECTING', 'QUOTED', 'AWAITING_CONFIRMATION', 'CONFIRMED', 'EXPIRED', 'CANCELLED') NOT NULL DEFAULT 'COLLECTING',
  `revision` INTEGER NOT NULL DEFAULT 1,
  `channel` ENUM('WHATSAPP', 'INSTAGRAM', 'FACEBOOK') NULL,
  `items` JSON NOT NULL,
  `customer` JSON NOT NULL,
  `fulfillment` JSON NOT NULL,
  `quoteSnapshot` JSON NULL,
  `quoteHash` VARCHAR(191) NULL,
  `quoteVersion` INTEGER NULL,
  `confirmationCodeHash` VARCHAR(191) NULL,
  `confirmationSalt` VARCHAR(191) NULL,
  `expiresAt` DATETIME(3) NULL,
  `idempotencyKey` VARCHAR(191) NOT NULL,
  `businessOrderId` VARCHAR(191) NULL,
  `businessOrderNumber` VARCHAR(191) NULL,
  `lastError` TEXT NULL,
  `confirmedAt` DATETIME(3) NULL,
  `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updatedAt` DATETIME(3) NOT NULL,

  PRIMARY KEY (`id`),
  UNIQUE INDEX `ConversationOrderDraft_idempotencyKey_key` (`idempotencyKey`),
  INDEX `ConversationOrderDraft_assistantId_state_updatedAt_idx` (`assistantId`, `state`, `updatedAt`),
  INDEX `ConversationOrderDraft_globalTenantId_state_updatedAt_idx` (`globalTenantId`, `state`, `updatedAt`),
  INDEX `ConversationOrderDraft_conversationId_state_updatedAt_idx` (`conversationId`, `state`, `updatedAt`),
  CONSTRAINT `ConversationOrderDraft_conversationId_fkey` FOREIGN KEY (`conversationId`) REFERENCES `Conversation`(`id`) ON DELETE CASCADE ON UPDATE CASCADE
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
