CREATE TABLE `BusinessOrderProjection` (
  `id` VARCHAR(191) NOT NULL,
  `globalTenantId` VARCHAR(191) NOT NULL,
  `assistantId` VARCHAR(191) NULL,
  `conversationId` VARCHAR(191) NULL,
  `businessOrderId` VARCHAR(191) NOT NULL,
  `orderNumber` VARCHAR(191) NOT NULL,
  `status` VARCHAR(191) NOT NULL,
  `channel` VARCHAR(191) NOT NULL,
  `currency` VARCHAR(191) NOT NULL,
  `subtotalAmount` DECIMAL(14, 2) NOT NULL DEFAULT 0,
  `shippingAmount` DECIMAL(14, 2) NOT NULL DEFAULT 0,
  `totalAmount` DECIMAL(14, 2) NOT NULL DEFAULT 0,
  `customerName` VARCHAR(191) NULL,
  `customerEmail` VARCHAR(191) NULL,
  `customerEmailNormalized` VARCHAR(191) NULL,
  `customerPhone` VARCHAR(191) NULL,
  `customerPhoneNormalized` VARCHAR(191) NULL,
  `items` JSON NOT NULL,
  `rawSnapshot` JSON NOT NULL,
  `version` INTEGER NOT NULL,
  `businessUpdatedAt` DATETIME(3) NOT NULL,
  `businessCreatedAt` DATETIME(3) NULL,
  `lastSyncedAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updatedAt` DATETIME(3) NOT NULL,

  PRIMARY KEY (`id`),
  UNIQUE INDEX `BusinessOrderProjection_globalTenantId_businessOrderId_key` (`globalTenantId`, `businessOrderId`),
  INDEX `BusinessOrderProjection_assistantId_businessUpdatedAt_idx` (`assistantId`, `businessUpdatedAt`),
  INDEX `BOP_tenant_channel_status_updated_idx` (`globalTenantId`, `channel`, `status`, `businessUpdatedAt`),
  INDEX `BusinessOrderProjection_conversationId_idx` (`conversationId`),
  INDEX `BusinessOrderProjection_customerEmailNormalized_idx` (`customerEmailNormalized`),
  INDEX `BusinessOrderProjection_customerPhoneNormalized_idx` (`customerPhoneNormalized`)
);
