import React, { useEffect, useState } from 'react';
import { getApiBase, getAdminTenantHeaders } from '../../../utils/api';

const input = 'w-full rounded-xl border border-white/20 bg-zinc-900/70 px-3 py-2.5 text-sm text-white outline-none focus:border-evolution-indigo focus:ring-2 focus:ring-evolution-indigo/30';
const initial = { smtp_from_name: '', email: '', order_notification_email: '', smtp_host: '', smtp_port: 465, smtp_secure: true, smtp_user: '', smtp_from: '', has_smtp_password: false };

export default function EmailEditor() {
  const [data, setData] = useState(initial); const [password, setPassword] = useState(''); const [to, setTo] = useState(''); const [status, setStatus] = useState(null); const [busy, setBusy] = useState(false);
  const headers = async () => {
    const token = localStorage.getItem('teflon_token');
    return { ...(await getAdminTenantHeaders()), 'Content-Type': 'application/json', ...(token ? { Authorization: `Bearer ${token}` } : {}) };
  };
  useEffect(() => { headers().then(authHeaders => fetch(`${getApiBase()}/api/admin/settings/email`, { headers: authHeaders })).then(r => r.ok ? r.json() : null).then(v => v && setData(v)); }, []);
  const request = async (path, options = {}) => { setBusy(true); setStatus(null); try { const r = await fetch(`${getApiBase()}/api/admin/settings/email${path}`, { headers: await headers(), ...options }); const body = await r.json(); setStatus({ ok: r.ok && (body.sent ?? body.verified ?? true), message: body.message || (body.sent ? 'Correo de prueba enviado correctamente.' : body.verified ? 'Conexión SMTP correcta.' : 'No se pudo completar la acción.') }); return body; } finally { setBusy(false); } };
  const save = async () => { const body = { ...data, smtp_password: password }; const saved = await request('', { method: 'PUT', body: JSON.stringify(body) }); if (saved?.smtp_host !== undefined) { setData(saved); setPassword(''); } };
  return <div className="space-y-6 pb-20"><div><p className="inline-flex rounded-full border border-evolution-indigo/30 bg-evolution-indigo/10 px-3 py-1 text-[11px] font-bold uppercase tracking-[.2em] text-indigo-100">Operación</p><h2 className="mt-3 text-2xl font-bold tracking-tight text-white">Correo</h2><p className="mt-1 max-w-2xl text-sm text-zinc-400">Configurá el servidor que envía verificaciones, confirmaciones y notificaciones.</p></div>
  <section className="space-y-4 rounded-2xl border border-white/10 bg-white/5 p-4"><h3 className="font-bold text-white">Identidad del correo</h3><div className="grid gap-3 md:grid-cols-3">{[['smtp_from_name','Nombre del remitente','Piquim'],['email','Email visible de la tienda','info@empresa.com'],['order_notification_email','Email de notificaciones','pedidos@empresa.com']].map(([key,label,placeholder])=><label key={key} className="space-y-1 text-xs font-bold uppercase tracking-widest text-zinc-400">{label}<input type="email" className={input} placeholder={placeholder} value={data[key]||''} onChange={e=>setData({...data,[key]:e.target.value})}/></label>)}</div></section>
  <section className="space-y-4 rounded-2xl border border-white/10 bg-white/5 p-4"><h3 className="font-bold text-white">Servidor SMTP</h3><p className="text-xs text-zinc-400">SSL/TLS suele usarse con 465; STARTTLS normalmente con 587.</p><div className="grid gap-3 md:grid-cols-2">{[['smtp_host','Host SMTP','mail.empresa.com','text'],['smtp_port','Puerto SMTP','465','number'],['smtp_user','Usuario SMTP','info@empresa.com','email'],['smtp_from','Email remitente','info@empresa.com','email']].map(([key,label,placeholder,type])=><label key={key} className="space-y-1 text-xs font-bold uppercase tracking-widest text-zinc-400">{label}<input type={type} className={input} placeholder={placeholder} value={data[key]||''} onChange={e=>setData({...data,[key]:type==='number'?Number(e.target.value):e.target.value})}/></label>)}<label className="space-y-1 text-xs font-bold uppercase tracking-widest text-zinc-400">Seguridad<select className={input} value={data.smtp_secure?'ssl':'starttls'} onChange={e=>setData({...data,smtp_secure:e.target.value==='ssl'})}><option value="ssl">SSL/TLS</option><option value="starttls">STARTTLS</option></select></label><label className="space-y-1 text-xs font-bold uppercase tracking-widest text-zinc-400">Contraseña SMTP<input type="password" autoComplete="new-password" className={input} placeholder={data.has_smtp_password?'Contraseña configurada':'Ingresá la contraseña'} value={password} onChange={e=>setPassword(e.target.value)}/></label></div><button disabled={busy} onClick={save} className="rounded-xl bg-evolution-indigo px-4 py-3 text-xs font-bold uppercase tracking-widest text-white disabled:opacity-50">{busy?'Guardando...':'Guardar correo'}</button></section>
  <section className="space-y-3 rounded-2xl border border-white/10 bg-white/5 p-4"><h3 className="font-bold text-white">Diagnóstico</h3><div className="flex flex-col gap-3 sm:flex-row"><button disabled={busy} onClick={()=>request('/verify',{method:'POST'})} className="rounded-xl border border-white/20 px-4 py-3 text-xs font-bold uppercase tracking-widest text-white disabled:opacity-50">Probar conexión</button><input type="email" className={input} placeholder="destinatario@ejemplo.com" value={to} onChange={e=>setTo(e.target.value)}/><button disabled={busy||!to} onClick={()=>request('/test',{method:'POST',body:JSON.stringify({to})})} className="rounded-xl border border-evolution-indigo/50 px-4 py-3 text-xs font-bold uppercase tracking-widest text-indigo-100 disabled:opacity-50">Enviar correo de prueba</button></div>{status&&<p role="status" className={status.ok?'text-sm text-emerald-300':'text-sm text-rose-300'}>{status.message}</p>}</section></div>;
}
